name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Destkop/Web, based on GoogleWebRTC.
homepage: https://github.com/cloudwebrtc/flutter-webrtc
version: 0.6.0
authors: 
  - cloudwebrtc <duanweiwei1982@gmail.com>
  - bsutton <bsutton@noojee.com.au>


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test:
    
flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      windows:
        pluginClass: FlutterWebRTCPlugin
